# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

export PATH=~/Library/Python/3.4/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/clairedranginis/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting bower brew npm osx)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
unsetopt nomatch

DEFAULT_USER=`whoami`
export VISUAL=vim
export EDITOR="$VISUAL"
# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# # Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line
# # Vi style:
# # zle -N edit-command-line
# # bindkey -M vicmd v edit-command-line

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export REMOTE_RETRO_GOOGLE_OAUTH_CLIENT_ID=295167791675-j1o5ucl3c3jeputmqk0aib205768gdsf.apps.googleusercontent.com
export REMOTE_RETRO_GOOGLE_OAUTH_CLIENT_SECRET=mNZX5ku2gNazD1fZhhoB6XJo
export REMOTE_RETRO_GOOGLE_OAUTH_REDIRECT_URI=http://localhost:4000/auth/google/callback

echo 'eval "$(pyenv init -)"' >> ~/.zshrc
echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
echo "export BPV2DEBUG='True'" >> ~/.zshrc
echo "export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'" >> ~/.zshrc
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export BPV2DEBUG='True'
export BPV2SECRET='i_%eb6^#j4yecsb+n1+3g9(=u%pli&dpq)(*w%m)yl480'
